import "Order.idl";

namespace ShowStart {
    [default_interface]
    runtimeclass OrderView : Microsoft.UI.Xaml.Controls.UserControl {
        OrderView();

        Windows.Foundation.Collections.IObservableVector<String> LogData { get; }; // 日志数据
        Windows.Foundation.Collections.IObservableVector<Order> Orders { get; }; // 下单数据
    }
}