namespace ShowStart {
    [default_interface]
    runtimeclass Order : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        Order(String mUserId, String mSign, String mIdCards);

        String UserId; // 用户ID
        String Sign; // 登录签名
        String IdCards; // 身份证信息
        String Log; // 日志
    }
}