import "Order.idl";

namespace ShowStart {
    [default_interface]
    runtimeclass OrderView : Microsoft.UI.Xaml.Controls.UserControl {
        OrderView();

        void SetID(String activity_id, String ticket_id);

        Windows.Foundation.Collections.IObservableVector<Order> Orders { get; };
    }
}